"""Readable names for the BiGG-style reaction ids in kinetic_params.xlsx.

The SBML files carry no descriptive names (name == id), so these are curated. The build checks every active reaction has
an entry and every entry names a real reaction. Names describe what the reaction does in this model, with the enzyme
named where it is not obvious from the id; 'abc' = ATP-driven ABC import, 't2r' = permease (no ATP), 'TRS' = tRNA charging.
"""

REACTIONS = {
    # ---- central metabolism (glycolysis, pentose phosphate, acetate)
    'PGI': 'Glucose-6-phosphate isomerase (G6P ⇌ F6P)',
    'PFK': 'Phosphofructokinase (F6P + ATP → FBP)',
    'FBA': 'Fructose-bisphosphate aldolase (FBP ⇌ DHAP + G3P)',
    'TPI': 'Triose-phosphate isomerase (DHAP ⇌ G3P)',
    'GAPD': 'Glyceraldehyde-3-phosphate dehydrogenase, NAD (G3P → 1,3-BPG)',
    'GAPDP': 'Glyceraldehyde-3-phosphate dehydrogenase, NADP (G3P → 3PG)',
    'PGK': 'Phosphoglycerate kinase (1,3-BPG + ADP → 3PG + ATP)',
    'PGM': 'Phosphoglycerate mutase (3PG ⇌ 2PG)',
    'ENO': 'Enolase (2PG ⇌ PEP)',
    'PYK': 'Pyruvate kinase (PEP + ADP → pyruvate + ATP)',
    'LDH_L': 'L-lactate dehydrogenase (pyruvate + NADH ⇌ lactate)',
    'PDH_acald': 'Pyruvate dehydrogenase, acetaldehyde branch (acetaldehyde + CoA → acetyl-CoA)',
    'PDH_E3': 'Dihydrolipoyl dehydrogenase (PDH E3: re-oxidises the lipoamide, makes NADH)',
    'PTAr': 'Phosphotransacetylase (acetyl-CoA + Pi ⇌ acetyl-phosphate)',
    'ACKr': 'Acetate kinase (acetyl-phosphate + ADP ⇌ acetate + ATP)',
    'NOX': 'NADH oxidase (2 NADH + O2 → 2 NAD+)',
    'RPE': 'Ribulose-5-phosphate 3-epimerase (Xu5P ⇌ Ru5P)',
    'RPI': 'Ribose-5-phosphate isomerase (Ru5P ⇌ R5P)',
    'TKT1': 'Transketolase 1 (G3P + S7P ⇌ R5P + Xu5P)',
    'TKT2': 'Transketolase 2 (F6P + G3P ⇌ E4P + Xu5P)',
    'TALA': 'Transaldolase (E4P + F6P ⇌ G3P + S7P)',
    'PRPPS': 'PRPP synthetase (R5P + ATP → PRPP + AMP)',
    'PPM': 'Phosphopentomutase (ribose-1-P ⇌ ribose-5-P)',
    'PPM2': 'Phosphopentomutase on deoxyribose (dR1P ⇌ dR5P)',
    'DRPA': 'Deoxyribose-phosphate aldolase (dR5P ⇌ acetaldehyde + G3P)',
    # ---- nucleotide metabolism
    'ADPT': 'Adenine phosphoribosyltransferase (adenine + PRPP → AMP)',
    'GUAPRT': 'Guanine phosphoribosyltransferase (guanine + PRPP → GMP)',
    'UPPRT': 'Uracil phosphoribosyltransferase (uracil + PRPP → UMP)',
    'ADK1': 'Adenylate kinase (AMP + ATP ⇌ 2 ADP)',
    'DADK': 'Adenylate kinase on dAMP (dAMP + ATP ⇌ dADP + ADP)',
    'GK1': 'Guanylate kinase (GMP + ATP ⇌ GDP + ADP)',
    'DGK1': 'Guanylate kinase on dGMP (dGMP + ATP ⇌ dGDP + ADP)',
    'CYTK1': 'Cytidylate kinase (CMP + ATP ⇌ CDP + ADP)',
    'CYTK2': 'Cytidylate kinase on dCMP (dCMP + ATP ⇌ dCDP + ADP)',
    'UMPK': 'UMP kinase (UMP + ATP ⇌ UDP + ADP)',
    'TMPK': 'dTMP kinase (dTMP + ATP ⇌ dTDP + ADP)',
    'CTPS2': 'CTP synthase (UTP + glutamine + ATP → CTP)',
    'CTPSDUMP': 'CTP synthase on dUMP (dUMP + glutamine + ATP → dCMP)',
    'DCMPDA': 'dCMP deaminase (dCMP → dUMP + NH3)',
    'DUTPDP': 'dUTP diphosphatase (dUTP → dUMP + PPi)',
    'RNDR1': 'Ribonucleotide reductase on ADP (ADP → dADP, thioredoxin-driven)',
    'RNDR2': 'Ribonucleotide reductase on GDP (GDP → dGDP, thioredoxin-driven)',
    'RNDR3': 'Ribonucleotide reductase on CDP (CDP → dCDP, thioredoxin-driven)',
    'RNDR4': 'Ribonucleotide reductase on UDP (UDP → dUDP, thioredoxin-driven)',
    'TRDR': 'Thioredoxin reductase (NADPH re-reduces thioredoxin)',
    'PUNP1': 'Purine nucleoside phosphorylase on adenosine (adenosine + Pi ⇌ adenine + R1P)',
    'PUNP2': 'Purine nucleoside phosphorylase on deoxyadenosine (→ adenine + dR1P)',
    'PUNP3': 'Purine nucleoside phosphorylase on guanosine (→ guanine + R1P)',
    'PUNP4': 'Purine nucleoside phosphorylase on deoxyguanosine (→ guanine + dR1P)',
    'PUNP5': 'Nucleoside phosphorylase on uridine (uridine + Pi ⇌ uracil + R1P)',
    'DADNK': 'Deoxyadenosine kinase (deoxyadenosine + ATP → dAMP)',
    'DCYTK': 'Deoxycytidine kinase (deoxycytidine + ATP → dCMP)',
    'DGSNK': 'Deoxyguanosine kinase (deoxyguanosine + ATP → dGMP)',
    'DURIK1': 'Deoxyuridine kinase (deoxyuridine + ATP → dUMP)',
    'TMDK1': 'Thymidine kinase (thymidine + ATP → dTMP)',
    'NTD1': "5'-nucleotidase on dUMP (dUMP → deoxyuridine + Pi)",
    'NTD5': "5'-nucleotidase on dTMP (dTMP → thymidine + Pi)",
    'NTD6': "5'-nucleotidase on dAMP (dAMP → deoxyadenosine + Pi)",
    'NTD8': "5'-nucleotidase on dGMP (dGMP → deoxyguanosine + Pi)",
    'PGK2': 'Phosphoglycerate kinase making dATP (1,3-BPG + dADP → 3PG + dATP)',
    'PGK3': 'Phosphoglycerate kinase making GTP (1,3-BPG + GDP → 3PG + GTP)',
    'PGK4': 'Phosphoglycerate kinase making dGTP (1,3-BPG + dGDP → 3PG + dGTP)',
    'PYK2': 'Pyruvate kinase making UTP (PEP + UDP → UTP)',
    'PYK3': 'Pyruvate kinase making GTP (PEP + GDP → GTP)',
    'PYK4': 'Pyruvate kinase making CTP (PEP + CDP → CTP)',
    'PYK5': 'Pyruvate kinase making dATP (PEP + dADP → dATP)',
    'PYK6': 'Pyruvate kinase making dGTP (PEP + dGDP → dGTP)',
    'PYK7': 'Pyruvate kinase making dCTP (PEP + dCDP → dCTP)',
    'PYK8': 'Pyruvate kinase making dTTP (PEP + dTDP → dTTP)',
    'PYK9': 'Pyruvate kinase making dUTP (PEP + dUDP → dUTP)',
    'PPA': 'Inorganic pyrophosphatase (PPi → 2 Pi)',
    # ---- lipid metabolism
    'GLYK': 'Glycerol kinase (glycerol + ATP → glycerol-3-P)',
    'FAKr': 'Fatty acid kinase (fatty acid + ATP → acyl-phosphate)',
    'APG3PAT': 'Acyl-phosphate:glycerol-3-P acyltransferase, PlsY (→ 1-acyl-G3P)',
    'ACPPAT': 'Acyl-phosphate:ACP transacylase, PlsX (acyl-P + ACP → acyl-ACP)',
    'AGPAT': '1-acyl-G3P acyltransferase, PlsC (1-acyl-G3P + acyl-ACP → phosphatidic acid)',
    'ACPS': 'Holo-ACP synthase (apo-ACP + CoA → ACP)',
    'BPNT': "3',5'-bisphosphate nucleotidase (PAP → AMP + Pi)",
    'DASYN': 'CDP-diacylglycerol synthase (phosphatidic acid + CTP → CDP-DAG)',
    'PGSA': 'Phosphatidylglycerophosphate synthase (CDP-DAG + glycerol-3-P → PGP)',
    'PGPP': 'Phosphatidylglycerophosphatase (PGP → phosphatidylglycerol)',
    'CLPNS': 'Cardiolipin synthase (2 PG → cardiolipin + glycerol)',
    'PAPA': 'Phosphatidate phosphatase (phosphatidic acid → diacylglycerol)',
    'PGMT': 'Phosphoglucomutase (G6P ⇌ G1P)',
    'GALU': 'UTP:glucose-1-P uridylyltransferase (G1P + UTP → UDP-glucose)',
    'UDPG4E': 'UDP-glucose 4-epimerase (UDP-glucose ⇌ UDP-galactose)',
    'UDPGALM': 'UDP-galactopyranose mutase (UDP-Gal ⇌ UDP-Gal-furanose)',
    'DAGGALT': 'Diacylglycerol galactosyltransferase (DAG + UDP-Galf → galactolipid)',
    # ---- cofactors
    'NCTPPRT': 'Nicotinate phosphoribosyltransferase (nicotinate + PRPP → NaMN)',
    'NNATr': 'NaMN adenylyltransferase (NaMN + ATP ⇌ deamido-NAD)',
    'NADS': 'NAD synthase (deamido-NAD + NH3 + ATP → NAD+)',
    'NADK': 'NAD kinase (NAD+ + ATP → NADP+)',
    'NADHK': 'NAD kinase on NADH (NADH + ATP → NADPH)',
    'RBFK': 'Riboflavin kinase (riboflavin + ATP → FMN)',
    'FMNAT': 'FMN adenylyltransferase (FMN + ATP → FAD)',
    '5FTHFPGS': 'Folylpolyglutamate synthase on 5-formyl-THF (adds two glutamates)',
    'FTHFCL': '5-formyl-THF cyclo-ligase (5-formyl-THF-Glu3 + ATP → 5,10-methenyl-THF)',
    'MTHFC': 'Methenyl-THF cyclohydrolase (5,10-methenyl-THF ⇌ 10-formyl-THF)',
    'MTHFD': 'Methylene-THF dehydrogenase (5,10-methylene-THF + NADP+ ⇌ 5,10-methenyl-THF)',
    'GHMT': 'Serine hydroxymethyltransferase (serine + THF ⇌ glycine + methylene-THF)',
    'GHMT2': 'Serine hydroxymethyltransferase side reaction (methenyl-THF → 5-formyl-THF)',
    'FMETTRS': 'Methionyl-tRNA formyltransferase (Met-tRNA + 10-formyl-THF → fMet-tRNA)',
    # ---- glucose PTS (protein phosphorelay, Non-Random-Binding sheet)
    'GLCpts0': 'Glucose PTS step 1: PEP phosphorylates Enzyme I',
    'GLCpts1': 'Glucose PTS step 2: Enzyme I~P phosphorylates HPr',
    'GLCpts2': 'Glucose PTS step 3: HPr~P phosphorylates IIA (Crr)',
    'GLCpts3': 'Glucose PTS step 4: IIA~P phosphorylates IIBC (PtsG)',
    'GLCpts4': 'Glucose PTS step 5: PtsG~P imports glucose as G6P',
    # ---- passive and fixed-rate transport (Non-Random-Binding sheet)
    'ACt': 'Acetate export (membrane permeability)',
    'L_LACt2r': 'L-lactate export (membrane permeability)',
    'PYRt2r': 'Pyruvate export (membrane permeability)',
    'CHOLt': 'Cholesterol uptake (fixed rate)',
    'FAt': 'Fatty acid uptake (fixed rate)',
    'GLYCt': 'Glycerol uptake (fixed rate)',
    'NAt': 'Sodium uptake (fixed rate)',
    'PCt': 'Phosphatidylcholine uptake (fixed rate)',
    'SMt': 'Sphingomyelin uptake (fixed rate)',
    'TAGt': 'Triacylglycerol uptake (fixed rate)',
    # ---- ATP-driven transport
    'ATPase': 'F0F1 ATP synthase (ADP + Pi ⇌ ATP)',
    'PIabc': 'Phosphate ABC import (Pst)',
    'Kt6': 'Potassium import / sodium export (Trk, ATP-driven)',
    'MG2abc': 'Magnesium import (MgtA P-type ATPase)',
    'CA2abc': 'Calcium import (CorA-type, ATP-driven)',
    'COAabc': 'Coenzyme A ABC import',
    'NACabc': 'Nicotinate ECF import',
    'RIBFLVabc': 'Riboflavin ECF import (RibU)',
    '5FTHFabc': '5-formyl-THF (folate) ECF import',
    'P5Pabc': "Pyridoxal 5'-phosphate ECF import",
    'THMPPabc': 'Thiamine pyrophosphate ABC import',
    'SPRMabc': 'Spermine ABC import (Pot)',
    'ADNabc': 'Adenosine ABC import (nucleoside transporter Rns/Upt)',
    'GSNabc': 'Guanosine ABC import (nucleoside transporter Rns/Upt)',
    'URIabc': 'Uridine ABC import (nucleoside transporter Rns/Upt)',
    'DADNabc': 'Deoxyadenosine ABC import (nucleoside transporter Rns/Upt)',
    'DGSNabc': 'Deoxyguanosine ABC import (nucleoside transporter Rns/Upt)',
    'DCYTabc': 'Deoxycytidine ABC import (nucleoside transporter Rns/Upt)',
    'THMDabc': 'Thymidine ABC import (nucleoside transporter Rns/Upt)',
    # ---- amino acid import: ABC (ATP) and permease (no ATP) routes in parallel
    'ALAabc': 'Alanine ABC import (oligopeptide transporter ATPase AmiF)',
    'ARGabc': 'Arginine ABC import (AmiF)',
    'ASNabc': 'Asparagine ABC import (AmiF)',
    'ASPabc': 'Aspartate ABC import (AmiF)',
    'GLNabc': 'Glutamine ABC import (AmiF)',
    'GLUabc': 'Glutamate ABC import (AmiF)',
    'GLYabc': 'Glycine ABC import (AmiF)',
    'HISabc': 'Histidine ABC import (AmiF)',
    'ILEabc': 'Isoleucine ABC import (AmiF)',
    'LEUabc': 'Leucine ABC import (AmiF)',
    'LYSabc': 'Lysine ABC import (AmiF)',
    'METabc': 'Methionine ABC import (AmiF)',
    'PHEabc': 'Phenylalanine ABC import (AmiF)',
    'PROabc': 'Proline ABC import (AmiF)',
    'SERabc': 'Serine ABC import (AmiF)',
    'THRabc': 'Threonine ABC import (AmiF)',
    'TRPabc': 'Tryptophan ABC import (AmiF)',
    'TYRabc': 'Tyrosine ABC import (AmiF)',
    'VALabc': 'Valine ABC import (AmiF)',
    'ALAt2r': 'Alanine permease import',
    'ARGt2r': 'Arginine permease import',
    'ASNt2r': 'Asparagine permease import',
    'ASPt2pr': 'Aspartate permease import',
    'CYSt2r': 'Cysteine permease import',
    'GLNt2r': 'Glutamine permease import',
    'GLUt2pr': 'Glutamate:proton symport (GltP)',
    'GLYt2r': 'Glycine permease import',
    'HISt2r': 'Histidine permease import',
    'ISOt2r': 'Isoleucine permease import',
    'LEUt2r': 'Leucine permease import',
    'LYSt2r': 'Lysine permease import',
    'METt2r': 'Methionine permease import',
    'PHEt2r': 'Phenylalanine permease import',
    'PROt2r': 'Proline permease import',
    'SERt2r': 'Serine permease import',
    'THRt2r': 'Threonine permease import',
    'TRPt2r': 'Tryptophan permease import',
    'TYRt2r': 'Tyrosine permease import',
    'VALt2r': 'Valine permease import',
    # ---- tRNA charging (CME)
    'ALATRS': 'Alanine tRNA charging (AlaRS)',
    'ARGTRS': 'Arginine tRNA charging (ArgRS)',
    'ASNTRS': 'Asparagine tRNA charging (AsnRS)',
    'ASPTRS': 'Aspartate tRNA charging (AspRS)',
    'CYSTRS': 'Cysteine tRNA charging (CysRS)',
    'GLNTRS': 'Glutamine tRNA charging (modelled on GatC, the Glu-tRNA amidotransferase route)',
    'GLUTRS': 'Glutamate tRNA charging (GluRS)',
    'GLYTRS': 'Glycine tRNA charging (GlyRS)',
    'HISTRS': 'Histidine tRNA charging (HisRS)',
    'ILETRS': 'Isoleucine tRNA charging (IleRS)',
    'LEUTRS': 'Leucine tRNA charging (LeuRS)',
    'LYSTRS': 'Lysine tRNA charging (LysRS)',
    'METTRS': 'Methionine tRNA charging (MetRS)',
    'PHETRS': 'Phenylalanine tRNA charging (PheRS α subunit)',
    'PROTRS': 'Proline tRNA charging (ProRS)',
    'SERTRS': 'Serine tRNA charging (SerRS)',
    'THRTRS': 'Threonine tRNA charging (ThrRS)',
    'TRPTRS': 'Tryptophan tRNA charging (TrpRS)',
    'TYRTRS': 'Tyrosine tRNA charging (TyrRS)',
    'VALTRS': 'Valine tRNA charging (ValRS)',
    # ---- not in the model (Other-Random-Binding sheet, never read)
    'GLCK': 'Glucokinase (glucose + ATP → G6P)',
    'GLCT': 'Glucose uniport',
}

ID_PARTS = [
    ['abc', 'ATP-driven ABC import from the medium'],
    ['t2r / t2pr', 'permease or symport, no ATP'],
    ['t (alone)', 'passive or fixed-rate transport'],
    ['TRS', 'tRNA synthetase (charging) reaction'],
    ['pts', 'phosphotransferase system (PEP-driven sugar import)'],
    ['PUNP / NTD / PYK n / PGK n', 'the same enzyme acting on different nucleotides, numbered'],
    ['r suffix', 'reversible in the source model'],
]


def check(reactions):
    """Every active reaction named; no names for reactions that do not exist."""
    missing = [rid for rid, r in reactions.items() if r['active'] and rid not in REACTIONS]
    extra = [rid for rid in REACTIONS if rid not in reactions]
    if missing or extra:
        raise RuntimeError('names.py: missing %s; unknown %s' % (missing, extra))
